groups:
  - name: node-alerts
    rules:
      - alert: InstanceDown
        expr: up{job="ec2-node-exporters"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is unreachable"
          description: "Target {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighCPUUsage
        expr: |
          100 * (1 - avg by (instance) (
            rate(node_cpu_seconds_total{job="ec2-node-exporters", mode="idle"}[5m])
          )) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage on {{ $labels.instance }} has exceeded 80% for 5 minutes."

      - alert: HighDiskUsage
        expr: |
          100 * (1 - (
            node_filesystem_avail_bytes{job="ec2-node-exporters", fstype!~"tmpfs|devtmpfs|overlay"}
            /
            node_filesystem_size_bytes{job="ec2-node-exporters", fstype!~"tmpfs|devtmpfs|overlay"}
          )) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Filesystem usage on {{ $labels.instance }} is above 85%."
